version: '3'
services:
  app1:
    build: ./app1
    networks:
      redpr:
        aliases:
          - app1
    ports:
      - "8585:8989"
  app2:
    build: ./app2
    networks:
      redpr:
        aliases:
          - app2
    ports:
      - "8585:8686"
networks:
  redpr:
